### ISSUE TITLE
Sharing data between master and workers in xdist

### ISSUE THREAD

**Issue by nicoddemus** [hackebrot/pytest-tricks#17]
Hi @hackebrot!

First of all congratulations on the idea of creating a pytest-tricks blog! 

I recently [posted](https://github.com/pytest-dev/pytest/issues/1402#issuecomment-186299177) a tip on how to share data between master and worker processes in xdist, I think it might be worth a blog post as I find that a neat trick. :smile:

**Comment by hackebrot** [comment]
Hi @nicoddemus! :bow: 

I would love to accept a PR from you! Have a look at [the source for the first post](https://github.com/hackebrot/pytest-tricks/tree/master/content/run_tests_using_fixture), copy the folder and rename it to what your post should be named. Edit the ``contents.lr`` file contained accordingly and you're done :smile_cat: 

Make sure to use Markdown instead of rst :wink:
